services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - ./bin:/app/bin
    depends_on:
      - postgres
    restart: "no"
    command: /app/bin/run-app.sh

  postgres:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "7432:${POSTGRES_PORT}"
    restart: "no"

volumes:
    db_data: {}
