services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - ./bin:/app/bin
    depends_on:
      - db
    restart: "no"
    command: /bin/bash /app/bin/run-app.sh

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "7432:7432"
    environment:
      POSTGRES_USER: python
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bwell
    restart: "no"

volumes:
    db_data: {}
